[2016-10-09 10:52:01] local.ERROR: exception 'Symfony\Component\Console\Exception\RuntimeException' with message 'Too many arguments, expected arguments "command".' in C:\xampp\htdocs\dev\laravel-auth\vendor\symfony\console\Input\ArgvInput.php:184
Stack trace:
#0 C:\xampp\htdocs\dev\laravel-auth\vendor\symfony\console\Input\ArgvInput.php(88): Symfony\Component\Console\Input\ArgvInput->parseArgument('down')
#1 C:\xampp\htdocs\dev\laravel-auth\vendor\symfony\console\Input\Input.php(62): Symfony\Component\Console\Input\ArgvInput->parse()
#2 C:\xampp\htdocs\dev\laravel-auth\vendor\symfony\console\Command\Command.php(221): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#3 C:\xampp\htdocs\dev\laravel-auth\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\xampp\htdocs\dev\laravel-auth\vendor\symfony\console\Application.php(820): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\xampp\htdocs\dev\laravel-auth\vendor\symfony\console\Application.php(187): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 C:\xampp\htdocs\dev\laravel-auth\vendor\symfony\console\Application.php(118): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 C:\xampp\htdocs\dev\laravel-auth\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 C:\xampp\htdocs\dev\laravel-auth\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 {main}  
[2016-10-09 11:13:59] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\Auth\RegisteredUser' not found' in C:\xampp\htdocs\dev\laravel-auth\app\Http\Controllers\Auth\RegisterController.php:49
Stack trace:
#0 {main}  
[2016-10-09 11:16:13] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\Auth\RegisteredUser' not found' in C:\xampp\htdocs\dev\laravel-auth\app\Http\Controllers\Auth\RegisterController.php:50
Stack trace:
#0 {main}  
[2016-10-09 11:59:54] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Routing\Route::get()' in C:\xampp\htdocs\dev\laravel-auth\routes\web.php:20
Stack trace:
#0 {main}  
